spring:
  datasource:
    url: jdbc:mysql://localhost/SpringcloudDemo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
#服务名称
  application:
    name: oauth2-sso-auth-server
#服务端口
server:
  port: 8006

#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  #是否显示IP地址
  instance:
    prefer-ip-address: true
    #此实例注册到eureka服务端的唯一的实例ID
    instance-id: user-6
