server:
  port: 8008
  servlet:
    context-path: /memberSystem
security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      access-token-uri: http://localhost:8006/oauth/token
      user-authorization-uri: http://localhost:8006/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8006/oauth/token_key
  #服务名称
spring:
  application:
    name: oauth2-sso-client-membe
#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  #是否显示IP地址
  instance:
    prefer-ip-address: true
    #此实例注册到eureka服务端的唯一的实例ID
    instance-id: user-8

